-- Migration: Create and populate standard lookup tables
-- Description: Pre-seed lookup tables for template tables (coins, comics, stamps, relics)
-- Created: 2026-01-02

-- ============================================================
-- STEP 1: Create lookup table registries
-- ============================================================

INSERT INTO custom_lookup_tables (table_name, display_name, created_by, is_shared, created_at) VALUES
  ('lookup_cointypes', 'Coin Types', 1, TRUE, CURRENT_TIMESTAMP),
  ('lookup_mintlocations', 'Mint Locations', 1, TRUE, CURRENT_TIMESTAMP),
  ('lookup_comicpublishers', 'Comic Book Publishers', 1, TRUE, CURRENT_TIMESTAMP),
  ('lookup_countries', 'Countries', 1, TRUE, CURRENT_TIMESTAMP),
  ('lookup_relictypes', 'Relic Types', 1, TRUE, CURRENT_TIMESTAMP)
ON CONFLICT (table_name) DO NOTHING;

-- ============================================================
-- STEP 2: Populate Coin Types (40+ entries with face_value)
-- ============================================================

INSERT INTO custom_lookup_values (lookup_table_id, value_data, display_order) VALUES
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Penny", "face_value": "0.01"}'::jsonb, 1),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Nickel", "face_value": "0.05"}'::jsonb, 2),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Dime", "face_value": "0.10"}'::jsonb, 3),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Quarter", "face_value": "0.25"}'::jsonb, 4),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Half Dollar", "face_value": "0.50"}'::jsonb, 5),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Dollar", "face_value": "1.00"}'::jsonb, 6),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Susan B. Anthony Dollar", "face_value": "1.00"}'::jsonb, 7),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Sacagawea Dollar", "face_value": "1.00"}'::jsonb, 8),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Presidential Dollar", "face_value": "1.00"}'::jsonb, 9),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Half Cent", "face_value": "0.005"}'::jsonb, 10),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Large Cent", "face_value": "0.01"}'::jsonb, 11),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Two Cent", "face_value": "0.02"}'::jsonb, 12),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Three Cent (Silver)", "face_value": "0.03"}'::jsonb, 13),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Three Cent (Nickel)", "face_value": "0.03"}'::jsonb, 14),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Half Dime", "face_value": "0.05"}'::jsonb, 15),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Twenty Cent", "face_value": "0.20"}'::jsonb, 16),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Quarter Dollar", "face_value": "0.25"}'::jsonb, 17),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Half Dollar (Historic)", "face_value": "0.50"}'::jsonb, 18),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Silver Dollar", "face_value": "1.00"}'::jsonb, 19),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Trade Dollar", "face_value": "1.00"}'::jsonb, 20),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Gold Dollar", "face_value": "1.00"}'::jsonb, 21),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Quarter Eagle", "face_value": "2.50"}'::jsonb, 22),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Three Dollar Gold", "face_value": "3.00"}'::jsonb, 23),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Four Dollar (Stella)", "face_value": "4.00"}'::jsonb, 24),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Half Eagle", "face_value": "5.00"}'::jsonb, 25),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Eagle", "face_value": "10.00"}'::jsonb, 26),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Double Eagle", "face_value": "20.00"}'::jsonb, 27),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "Panama-Pacific $50 Gold", "face_value": "50.00"}'::jsonb, 28),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Silver Eagle", "face_value": "1.00"}'::jsonb, 29),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Gold Eagle $5", "face_value": "5.00"}'::jsonb, 30),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Gold Eagle $10", "face_value": "10.00"}'::jsonb, 31),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Gold Eagle $25", "face_value": "25.00"}'::jsonb, 32),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Gold Eagle $50", "face_value": "50.00"}'::jsonb, 33),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Platinum Eagle $10", "face_value": "10.00"}'::jsonb, 34),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Platinum Eagle $25", "face_value": "25.00"}'::jsonb, 35),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Platinum Eagle $50", "face_value": "50.00"}'::jsonb, 36),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Platinum Eagle $100", "face_value": "100.00"}'::jsonb, 37),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Palladium Eagle $25", "face_value": "25.00"}'::jsonb, 38),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Buffalo Gold $50", "face_value": "50.00"}'::jsonb, 39),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_cointypes'),
   '{"name": "American Liberty $100", "face_value": "100.00"}'::jsonb, 40);

-- ============================================================
-- STEP 3: Populate Mint Locations (9 historical US mints)
-- ============================================================

INSERT INTO custom_lookup_values (lookup_table_id, value_data, display_order) VALUES
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "Philadelphia Mint", "city": "Philadelphia", "state": "Pennsylvania"}'::jsonb, 1),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "Denver Mint", "city": "Denver", "state": "Colorado"}'::jsonb, 2),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "San Francisco Mint", "city": "San Francisco", "state": "California"}'::jsonb, 3),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "West Point Mint", "city": "West Point", "state": "New York"}'::jsonb, 4),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "Carson City Mint", "city": "Carson City", "state": "Nevada"}'::jsonb, 5),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "New Orleans Mint", "city": "New Orleans", "state": "Louisiana"}'::jsonb, 6),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "Charlotte Mint", "city": "Charlotte", "state": "North Carolina"}'::jsonb, 7),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "Dahlonega Mint", "city": "Dahlonega", "state": "Georgia"}'::jsonb, 8),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_mintlocations'),
   '{"name": "Manila Mint", "city": "Manila", "state": "Philippines"}'::jsonb, 9);

-- ============================================================
-- STEP 4: Populate Comic Publishers (30+ publishers)
-- ============================================================

INSERT INTO custom_lookup_values (lookup_table_id, value_data, display_order) VALUES
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Marvel Comics"}'::jsonb, 1),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "DC Comics"}'::jsonb, 2),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Image Comics"}'::jsonb, 3),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Dark Horse Comics"}'::jsonb, 4),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "IDW Publishing"}'::jsonb, 5),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "BOOM! Studios"}'::jsonb, 6),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Valiant Entertainment"}'::jsonb, 7),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Dynamite Entertainment"}'::jsonb, 8),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Archie Comics"}'::jsonb, 9),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Aspen Comics"}'::jsonb, 10),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Gold Key Comics"}'::jsonb, 11),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Dell Comics"}'::jsonb, 12),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Charlton Comics"}'::jsonb, 13),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Harvey Comics"}'::jsonb, 14),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Fawcett Comics"}'::jsonb, 15),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Quality Comics"}'::jsonb, 16),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Timely Comics"}'::jsonb, 17),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Atlas Comics"}'::jsonb, 18),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "EC Comics"}'::jsonb, 19),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Fiction House"}'::jsonb, 20),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Fox Feature Syndicate"}'::jsonb, 21),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Nedor Comics"}'::jsonb, 22),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "St. John Publications"}'::jsonb, 23),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Oni Press"}'::jsonb, 24),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Rebellion"}'::jsonb, 25),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Zenescope Entertainment"}'::jsonb, 26),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Top Cow Productions"}'::jsonb, 27),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Vertigo (DC Imprint)"}'::jsonb, 28),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "MAX (Marvel Imprint)"}'::jsonb, 29),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Ultimate Marvel"}'::jsonb, 30),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "WildStorm"}'::jsonb, 31),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_comicpublishers'),
   '{"name": "Other"}'::jsonb, 32);

-- ============================================================
-- STEP 5: Populate Countries (ISO 3166-1 country list)
-- ============================================================

INSERT INTO custom_lookup_values (lookup_table_id, value_data, display_order) VALUES
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Afghanistan", "code": "AF"}'::jsonb, 1),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Albania", "code": "AL"}'::jsonb, 2),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Algeria", "code": "DZ"}'::jsonb, 3),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Andorra", "code": "AD"}'::jsonb, 4),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Angola", "code": "AO"}'::jsonb, 5),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Antigua and Barbuda", "code": "AG"}'::jsonb, 6),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Argentina", "code": "AR"}'::jsonb, 7),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Armenia", "code": "AM"}'::jsonb, 8),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Australia", "code": "AU"}'::jsonb, 9),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Austria", "code": "AT"}'::jsonb, 10),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Azerbaijan", "code": "AZ"}'::jsonb, 11),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Bahamas", "code": "BS"}'::jsonb, 12),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Bahrain", "code": "BH"}'::jsonb, 13),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Bangladesh", "code": "BD"}'::jsonb, 14),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Barbados", "code": "BB"}'::jsonb, 15),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Belarus", "code": "BY"}'::jsonb, 16),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Belgium", "code": "BE"}'::jsonb, 17),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Belize", "code": "BZ"}'::jsonb, 18),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Benin", "code": "BJ"}'::jsonb, 19),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Bhutan", "code": "BT"}'::jsonb, 20),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Bolivia", "code": "BO"}'::jsonb, 21),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Bosnia and Herzegovina", "code": "BA"}'::jsonb, 22),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Botswana", "code": "BW"}'::jsonb, 23),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Brazil", "code": "BR"}'::jsonb, 24),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Brunei", "code": "BN"}'::jsonb, 25),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Bulgaria", "code": "BG"}'::jsonb, 26),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Burkina Faso", "code": "BF"}'::jsonb, 27),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Burundi", "code": "BI"}'::jsonb, 28),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Cambodia", "code": "KH"}'::jsonb, 29),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Cameroon", "code": "CM"}'::jsonb, 30),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Canada", "code": "CA"}'::jsonb, 31),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Cape Verde", "code": "CV"}'::jsonb, 32),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Central African Republic", "code": "CF"}'::jsonb, 33),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Chad", "code": "TD"}'::jsonb, 34),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Chile", "code": "CL"}'::jsonb, 35),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "China", "code": "CN"}'::jsonb, 36),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Colombia", "code": "CO"}'::jsonb, 37),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Comoros", "code": "KM"}'::jsonb, 38),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Congo", "code": "CG"}'::jsonb, 39),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Costa Rica", "code": "CR"}'::jsonb, 40),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Croatia", "code": "HR"}'::jsonb, 41),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Cuba", "code": "CU"}'::jsonb, 42),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Cyprus", "code": "CY"}'::jsonb, 43),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Czech Republic", "code": "CZ"}'::jsonb, 44),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Denmark", "code": "DK"}'::jsonb, 45),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Djibouti", "code": "DJ"}'::jsonb, 46),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Dominica", "code": "DM"}'::jsonb, 47),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Dominican Republic", "code": "DO"}'::jsonb, 48),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "East Timor", "code": "TL"}'::jsonb, 49),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Ecuador", "code": "EC"}'::jsonb, 50),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Egypt", "code": "EG"}'::jsonb, 51),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "El Salvador", "code": "SV"}'::jsonb, 52),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Equatorial Guinea", "code": "GQ"}'::jsonb, 53),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Eritrea", "code": "ER"}'::jsonb, 54),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Estonia", "code": "EE"}'::jsonb, 55),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Ethiopia", "code": "ET"}'::jsonb, 56),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Fiji", "code": "FJ"}'::jsonb, 57),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Finland", "code": "FI"}'::jsonb, 58),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "France", "code": "FR"}'::jsonb, 59),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Gabon", "code": "GA"}'::jsonb, 60),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Gambia", "code": "GM"}'::jsonb, 61),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Georgia", "code": "GE"}'::jsonb, 62),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Germany", "code": "DE"}'::jsonb, 63),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Ghana", "code": "GH"}'::jsonb, 64),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Greece", "code": "GR"}'::jsonb, 65),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Grenada", "code": "GD"}'::jsonb, 66),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Guatemala", "code": "GT"}'::jsonb, 67),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Guinea", "code": "GN"}'::jsonb, 68),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Guinea-Bissau", "code": "GW"}'::jsonb, 69),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Guyana", "code": "GY"}'::jsonb, 70),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Haiti", "code": "HT"}'::jsonb, 71),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Honduras", "code": "HN"}'::jsonb, 72),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Hungary", "code": "HU"}'::jsonb, 73),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Iceland", "code": "IS"}'::jsonb, 74),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "India", "code": "IN"}'::jsonb, 75),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Indonesia", "code": "ID"}'::jsonb, 76),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Iran", "code": "IR"}'::jsonb, 77),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Iraq", "code": "IQ"}'::jsonb, 78),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Ireland", "code": "IE"}'::jsonb, 79),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Israel", "code": "IL"}'::jsonb, 80),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Italy", "code": "IT"}'::jsonb, 81),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Jamaica", "code": "JM"}'::jsonb, 82),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Japan", "code": "JP"}'::jsonb, 83),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Jordan", "code": "JO"}'::jsonb, 84),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Kazakhstan", "code": "KZ"}'::jsonb, 85),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Kenya", "code": "KE"}'::jsonb, 86),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Kiribati", "code": "KI"}'::jsonb, 87),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "North Korea", "code": "KP"}'::jsonb, 88),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "South Korea", "code": "KR"}'::jsonb, 89),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Kuwait", "code": "KW"}'::jsonb, 90),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Kyrgyzstan", "code": "KG"}'::jsonb, 91),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Laos", "code": "LA"}'::jsonb, 92),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Latvia", "code": "LV"}'::jsonb, 93),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Lebanon", "code": "LB"}'::jsonb, 94),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Lesotho", "code": "LS"}'::jsonb, 95),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Liberia", "code": "LR"}'::jsonb, 96),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Libya", "code": "LY"}'::jsonb, 97),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Liechtenstein", "code": "LI"}'::jsonb, 98),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Lithuania", "code": "LT"}'::jsonb, 99),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Luxembourg", "code": "LU"}'::jsonb, 100),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Macedonia", "code": "MK"}'::jsonb, 101),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Madagascar", "code": "MG"}'::jsonb, 102),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Malawi", "code": "MW"}'::jsonb, 103),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Malaysia", "code": "MY"}'::jsonb, 104),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Maldives", "code": "MV"}'::jsonb, 105),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Mali", "code": "ML"}'::jsonb, 106),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Malta", "code": "MT"}'::jsonb, 107),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Marshall Islands", "code": "MH"}'::jsonb, 108),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Mauritania", "code": "MR"}'::jsonb, 109),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Mauritius", "code": "MU"}'::jsonb, 110),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Mexico", "code": "MX"}'::jsonb, 111),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Micronesia", "code": "FM"}'::jsonb, 112),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Moldova", "code": "MD"}'::jsonb, 113),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Monaco", "code": "MC"}'::jsonb, 114),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Mongolia", "code": "MN"}'::jsonb, 115),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Montenegro", "code": "ME"}'::jsonb, 116),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Morocco", "code": "MA"}'::jsonb, 117),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Mozambique", "code": "MZ"}'::jsonb, 118),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Myanmar", "code": "MM"}'::jsonb, 119),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Namibia", "code": "NA"}'::jsonb, 120),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Nauru", "code": "NR"}'::jsonb, 121),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Nepal", "code": "NP"}'::jsonb, 122),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Netherlands", "code": "NL"}'::jsonb, 123),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "New Zealand", "code": "NZ"}'::jsonb, 124),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Nicaragua", "code": "NI"}'::jsonb, 125),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Niger", "code": "NE"}'::jsonb, 126),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Nigeria", "code": "NG"}'::jsonb, 127),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Norway", "code": "NO"}'::jsonb, 128),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Oman", "code": "OM"}'::jsonb, 129),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Pakistan", "code": "PK"}'::jsonb, 130),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Palau", "code": "PW"}'::jsonb, 131),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Panama", "code": "PA"}'::jsonb, 132),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Papua New Guinea", "code": "PG"}'::jsonb, 133),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Paraguay", "code": "PY"}'::jsonb, 134),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Peru", "code": "PE"}'::jsonb, 135),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Philippines", "code": "PH"}'::jsonb, 136),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Poland", "code": "PL"}'::jsonb, 137),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Portugal", "code": "PT"}'::jsonb, 138),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Qatar", "code": "QA"}'::jsonb, 139),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Romania", "code": "RO"}'::jsonb, 140),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Russia", "code": "RU"}'::jsonb, 141),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Rwanda", "code": "RW"}'::jsonb, 142),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Saint Kitts and Nevis", "code": "KN"}'::jsonb, 143),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Saint Lucia", "code": "LC"}'::jsonb, 144),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Saint Vincent and the Grenadines", "code": "VC"}'::jsonb, 145),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Samoa", "code": "WS"}'::jsonb, 146),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "San Marino", "code": "SM"}'::jsonb, 147),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Sao Tome and Principe", "code": "ST"}'::jsonb, 148),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Saudi Arabia", "code": "SA"}'::jsonb, 149),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Senegal", "code": "SN"}'::jsonb, 150),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Serbia", "code": "RS"}'::jsonb, 151),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Seychelles", "code": "SC"}'::jsonb, 152),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Sierra Leone", "code": "SL"}'::jsonb, 153),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Singapore", "code": "SG"}'::jsonb, 154),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Slovakia", "code": "SK"}'::jsonb, 155),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Slovenia", "code": "SI"}'::jsonb, 156),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Solomon Islands", "code": "SB"}'::jsonb, 157),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Somalia", "code": "SO"}'::jsonb, 158),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "South Africa", "code": "ZA"}'::jsonb, 159),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "South Sudan", "code": "SS"}'::jsonb, 160),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Spain", "code": "ES"}'::jsonb, 161),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Sri Lanka", "code": "LK"}'::jsonb, 162),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Sudan", "code": "SD"}'::jsonb, 163),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Suriname", "code": "SR"}'::jsonb, 164),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Swaziland", "code": "SZ"}'::jsonb, 165),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Sweden", "code": "SE"}'::jsonb, 166),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Switzerland", "code": "CH"}'::jsonb, 167),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Syria", "code": "SY"}'::jsonb, 168),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Taiwan", "code": "TW"}'::jsonb, 169),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Tajikistan", "code": "TJ"}'::jsonb, 170),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Tanzania", "code": "TZ"}'::jsonb, 171),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Thailand", "code": "TH"}'::jsonb, 172),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Togo", "code": "TG"}'::jsonb, 173),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Tonga", "code": "TO"}'::jsonb, 174),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Trinidad and Tobago", "code": "TT"}'::jsonb, 175),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Tunisia", "code": "TN"}'::jsonb, 176),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Turkey", "code": "TR"}'::jsonb, 177),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Turkmenistan", "code": "TM"}'::jsonb, 178),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Tuvalu", "code": "TV"}'::jsonb, 179),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Uganda", "code": "UG"}'::jsonb, 180),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Ukraine", "code": "UA"}'::jsonb, 181),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "United Arab Emirates", "code": "AE"}'::jsonb, 182),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "United Kingdom", "code": "GB"}'::jsonb, 183),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "United States", "code": "US"}'::jsonb, 184),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Uruguay", "code": "UY"}'::jsonb, 185),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Uzbekistan", "code": "UZ"}'::jsonb, 186),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Vanuatu", "code": "VU"}'::jsonb, 187),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Vatican City", "code": "VA"}'::jsonb, 188),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Venezuela", "code": "VE"}'::jsonb, 189),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Vietnam", "code": "VN"}'::jsonb, 190),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Yemen", "code": "YE"}'::jsonb, 191),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Zambia", "code": "ZM"}'::jsonb, 192),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_countries'),
   '{"name": "Zimbabwe", "code": "ZW"}'::jsonb, 193);

-- ============================================================
-- STEP 6: Populate Relic Types (6 types)
-- ============================================================

INSERT INTO custom_lookup_values (lookup_table_id, value_data, display_order) VALUES
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_relictypes'),
   '{"name": "Arrowhead"}'::jsonb, 1),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_relictypes'),
   '{"name": "Pottery"}'::jsonb, 2),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_relictypes'),
   '{"name": "Tool"}'::jsonb, 3),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_relictypes'),
   '{"name": "Jewelry"}'::jsonb, 4),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_relictypes'),
   '{"name": "Weapon"}'::jsonb, 5),
  ((SELECT id FROM custom_lookup_tables WHERE table_name = 'lookup_relictypes'),
   '{"name": "Other"}'::jsonb, 6);
